# Generated by Django 4.2.1 on 2023-05-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_friends_friendchain"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendchain",
            name="is_subscriber",
            field=models.BooleanField(default=False),
        ),
    ]
