# Generated by Django 4.2.1 on 2023-05-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_friendchain_is_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendchain',
            old_name='is_subscriber',
            new_name='was_rejected',
        ),
    ]
